version: '3.8'

services:
  postgres-environments:
    image: postgres:14.2
    container_name: environment-service-db
    environment:
      POSTGRES_PASSWORD: ${PG_ENV_PASSWORD}
      POSTGRES_USER: ${PG_ENV_USER}
      POSTGRES_DB: ${PG_ENV_DATABASE}
    ports:
      - 5433:5432
    volumes:
      - ./data/environments:/var/lib/postgresql/data
