version: '3.8'

services:
  postgres-devices:
    image: postgres:14.2
    container_name: devices-service-db
    environment:
      POSTGRES_PASSWORD: ${PG_DEVICES_PASSWORD}
      POSTGRES_USER: ${PG_DEVICES_USER}
      POSTGRES_DB: ${PG_DEVICES_DB}
    ports:
      - ${PG_DEVICES_PORT}:5432
    volumes:
      - ./data/devices:/var/lib/postgresql/data
