-- DropForeignKey
ALTER TABLE "Esp8266" DROP CONSTRAINT "Esp8266_esp32Id_fkey";

-- AlterTable
ALTER TABLE "Esp8266" ALTER COLUMN "esp32Id" DROP NOT NULL;

-- AddForeignKey
ALTER TABLE "Esp8266" ADD CONSTRAINT "Esp8266_esp32Id_fkey" FOREIGN KEY ("esp32Id") REFERENCES "Esp32"("id") ON DELETE SET NULL ON UPDATE CASCADE;
