name: Continuous Integration and Continuous Deployment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Using Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.x

      - name: Install dependencies, run tests and build Access service
        run: cd access && npm install && npm run build

      - name: Install dependencies, run tests and build Audit service
        run: cd audit && npm install && npm run build

      - name: Install dependencies, run tests and build Devices service
        run: cd devices && npm install && npm run build

      - name: Install dependencies, run tests and build Environments service
        run: cd environments && npm install && npm run build
      
      - name: Install dependencies, run tests and build Gateway service
        run: cd gateway && npm install && npm run build

      - name: Install dependencies, run tests and build Tokenization service
        run: cd tokenization && npm install && npm run build
      
      - name: Install dependencies, run tests and build Users service
        run: cd users && npm install && npm run build
        
  CD:
    runs-on: ubuntu-latest

    needs: CI

    steps:
      - name: Set up keys
        uses: kielabokkie/ssh-key-and-known-hosts-action@v1
        with:
          ssh-private-key: ${{ secrets.LAICA_CD_KEY }}
          ssh-host: laica.ifrn.edu.br

      - name: Deploy
        run: make deploy
